COOKIE_PASSWORD = "89292398929239608489292396084"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true


# .streamlit/secrets.toml
firebase_api_key = "AIzaSyCj0UPv444P-C6ggFZ8Q_NXvSSBraHeDG4"


[firebase_service_account]
type = "service_account"
project_id = "login1-e7ab2"
private_key_id = "6855119f0a3452ac6f36edc34086ebddd4997380"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeoneJAqvbA2E9
7f6vU7iN4tNN0y94kTPQEoWaJ7STQjmSFx21myx2Kker/W4nxah6zOO/Kgjwyo+E
jMmV8w6XckjAp9j3426IbfCfY1PxuOAWdRR1m20QtA6rIbHPL/Nk9zRONbcJkxij
8zz4Pch9e1YHBIhqEGtrdaZNxA1qZ71TNTsHL8AWzKL0lTrKruzhznnaA07Nw3c5
2YQd+9Jxke1q0F85feshGfaqvamESxrLmzcZOeIsypf15CD9qgkDr/o8bddMdTzm
h+BhdZ0ZnYZRwx/Npzvj44T0YPyStlf9OohiizyN8zAWEfBagnSRdWXh5Or5N5JN
hIrisM/FAgMBAAECggEAI7lGHQIEuXvtWpaZy2BPuNSwu0gr0djay4RtU7MTUp3J
xxtWdRGVLNDT91EPH+qjgjDmSoJgNOML7GT648jAiqSX7/H+6qff0Jxzg9/YVG0p
5/CZe9WYxpld0S/y7B/xmj3gcrxDxpGH3qblHaAsT5Y+05lymjJQSknyiX/v9yap
eoWFs4g4AzjgPQ+109K3ynqMm1fkkUrp3BEup5ht3lGqNxD74g1eepLec28VQAJF
URkJ2e9//BHCA91SnTKHIFdgUg0/AC/O5y3v6rvjiqyq4KO+6jDpZ/3cQCu2k6Hw
3SBonb/9kvxP5ZR+WN9E1ttpEZjYPv8XXdVzrq+x8QKBgQD/uLop2YYnAXNoihsd
wTMOjVmIFRzzo+EmgXAtAtUwyqtjvUWo+TDfjvqLUQCQPmMUzC9hE/hcpQGDh3aD
a30TP/fxFcVcDjBRNlHGTnFQDV8pdLLTXkBCBs5gafL8dMyh3EK6xDFiYKEGIFDY
ObwPzaKg0EbGaT1zjQi3D09diwKBgQDe4ISavoKorVR4TK5uW10ChkGNbScD+9aN
s8LDE5Pyy9EzF+UzAzdRSwGACRMQiAkyOLfQfr9hm/9EZeARlMbnFp8wW8l3UDcd
kbZeBqekO9rnl3lHtshce6CtAvs5roC6iIthxXsrzXUmHcQdWmHDXLJYeH863YEG
YrD1H+7R7wKBgQD8YKwasXwc8umbuvGYJBznt8ks7Olt68dB4W18ftc5GEyeWyZs
5cK+YLYU2RTdRzUySXJZNQRhKtibnw3wFh2S6gciAIKPn9E/1YRPWwuqHghVOb9j
rBlvEJiNvwL49a0f8epJuWej2AoTqcEgJZrdXe2rGONA3oyvhfmb8Zg6kQKBgQC7
jLlpsnkm0jzrwrNiQFXDYxDUnw6e5pSEx8lT+Syduu+/DBOeWs15BiIsCPbXCXKb
pWjg9Ve9HtWvS/9DLCw4mCu7OPIPChxnMJADDZySsp+iFTBErcZrNMlf7ctUncjL
r02DJ/hfQtSbD59RiBYOnPmjQzrlYTJLGk+I5qdEVwKBgHrpH53Rjpqqremd5ua+
++GEgHh1t39Yp5EX5G7WC9sT5YL1tXNLBvs5BnH8uKnt4t5aypto66J9lHd76rvk
Io1rplOHIxOprqaOnXtJDKYQRaxsl80gKvxM+HiTNNtnsRiIQ6S6a9nv3Mbr/wWx
xVj7bDFdJOtuSbf3ZAcsv0uJ
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@login1-e7ab2.iam.gserviceaccount.com"
client_id = "109536071117363121755"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40login1-e7ab2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
